### ISSUE TITLE
problem about use object models

### ISSUE THREAD

**Issue by vincentkeino** [facebookresearch/TCDM#2]
hi,thanks for provide code,i want to use object models in my work,but while i use the xml of airplane ,it reported this error:"Error: eigenvalue of mesh inertia too small: airplan",i tried to improve mass or density,but it did not work, could you tell me how to solve this problem,thank u!

**Comment by vikashplus** [comment]
It seems you are trying to use the object model outside of this repository. How you are tying to use them is beyond the scope if this repository. I'll recommend going through the [MuJoCo documentation](https://mujoco.org/) to understand the details. 

Tip: from the errors it seems like the inertia is getting computed form the mesh. Try explicitly specifying the inertia (if you have reasonable estimates).
